import { useEffect } from "react";
import { useLiveBackground } from "../components/LiveBackground";
import SelectProviderForVerification from "../components/SelectProviderForVerification/index";
import WordLogo from "../components/logo/WordLogo";

function Page() {
  const { setStatus } = useLiveBackground();
  useEffect(() => {
    setStatus("idle");
  }, [setStatus]);

  return (
    <div className="container">
      <WordLogo />

      <h1 className="main-heading">Reclaim Protocol Demo</h1>

      <p className="subheading">What do you want to verify?</p>

      <SelectProviderForVerification />
      <p className="disclaimer">
        Proofs generated by Reclaim Protocol are secure and private.{" "}
        <a
          href="https://docs.reclaimprotocol.org"
          className="link"
          target="_blank"
          rel="noreferrer"
        >
          Learn More
        </a>
      </p>
    </div>
  );
}

export default Page;
